#spring.application.name=question-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_lcwd
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8091


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0


