

#spring.application.name=quiz-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro_lcwd
    username: root
    password: root
  jpa:
    show-sql: true   #to see the queries
    hibernate:
      ddl-auto: update #with this table will be automatically created based on the entity created

question:
  url: http://localhost:8091/question

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0


server:
  port: 8090
